[package]
name = "wayland-window"
version = "0.1.0"
authors = ["Victor Berger <victor.berger@m4x.org>"]
repository = "https://github.com/vberger/wayland-window"
documentation = "http://vberger.github.io/wayland-window/wayland_window/"
license = "MIT"
description = "A simple window-decorations library built on top of wayland-client."

[dependencies]
byteorder = "0.3"
tempfile = "1.1"
wayland-client = "^0.2.1"

[dev-dependencies]
wayland-client = { features = ["dlopen"] }